name: Build Jekyll Site

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Specify Ruby version compatible with your Jekyll version
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Upload built site as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site